name: DAST (ZAP Baseline)

on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
      max_time:
        type: number
        default: 5
      artifact_name:
        type: string
        default: "zap-report"

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create results files
        run: |
          touch report_html.html report_json.json
          chmod a+w report_html.html report_json.json

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ inputs.target }}
          fail_action: true
          cmd_options: "-m ${{ inputs.max_time }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}-${{ github.run_id }}
          path: |
            report_html.html
            report_json.json
          if-no-files-found: ignore
