name: IaC Validate & tfsec

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        default: "infra"
      tf_version:
        type: string
        default: "1.8.5"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Terraform fmt/validate/plan
        working-directory: ${{ inputs.working_dir }}
        run: |
          terraform init -input=false
          terraform fmt -check
          terraform validate
          terraform plan -out=tfplan

      # ✅ Use a real tag and correct inputs
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ inputs.working_dir }}
          # optional:
          # format: sarif
          # additional_args: --minimum-severity HIGH
          # soft_fail: false
          # github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: ${{ inputs.working_dir }}/tfplan
