name: IaC Validate & tfsec (auto-discover)

on:
  workflow_call:
    inputs:
      tf_version:
        type: string
        default: "1.8.5"

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.mk.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: mk
        name: Build directory matrix
        shell: bash
        run: |
          # List unique dirs containing .tf files, ignore .git and hidden dirs
          mapfile -t dirs < <(find . -type f -name "*.tf" -not -path "*/.*/*" -printf '%h\n' | sort -u)
          if [ ${#dirs[@]} -eq 0 ]; then
            echo "matrix={\"dir\":[]}" >> "$GITHUB_OUTPUT"
          else
            json=$(printf '%s\n' "${dirs[@]}" | jq -R . | jq -s '{dir: .}')
            echo "matrix=$json" >> "$GITHUB_OUTPUT"
          fi

  terraform:
    needs: discover
    if: ${{ fromJson(needs.discover.outputs.matrix).dir != null && fromJson(needs.discover.outputs.matrix).dir.size() > 0 }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Terraform fmt/validate/plan
        run: |
          terraform -chdir="${{ matrix.dir }}" init -input=false
          terraform -chdir="${{ matrix.dir }}" fmt -check
          terraform -chdir="${{ matrix.dir }}" validate
          terraform -chdir="${{ matrix.dir }}" plan -out=tfplan

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ matrix.dir }}

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-${{ hashFiles(format('{0}/**/*.tf', matrix.dir)) }}
          path: ${{ matrix.dir }}/tfplan

  no_tf:
    needs: discover
    if: ${{ !(fromJson(needs.discover.outputs.matrix).dir != null && fromJson(needs.discover.outputs.matrix).dir.size() > 0) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "No Terraform files found. Skipping IaC job."
