name: IaC Validate & tfsec

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        default: "infra"
      tf_version:
        type: string
        default: "1.8.5"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version }}

      # Quickly check if the directory exists AND has any .tf files
      - name: Check Terraform dir
        id: check_dir
        shell: bash
        run: |
          dir="${{ inputs.working_dir }}"
          if [ -d "$dir" ] && compgen -G "$dir/**/*.tf" > /dev/null || compgen -G "$dir/*.tf" > /dev/null; then
            echo "has_tf=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_tf=false" >> "$GITHUB_OUTPUT"
            echo "No Terraform files found in '$dir'. Skipping."
          fi

      - name: Terraform fmt/validate/plan
        if: ${{ steps.check_dir.outputs.has_tf == 'true' }}
        run: |
          terraform -chdir="${{ inputs.working_dir }}" init -input=false
          terraform -chdir="${{ inputs.working_dir }}" fmt -check
          terraform -chdir="${{ inputs.working_dir }}" validate
          terraform -chdir="${{ inputs.working_dir }}" plan -out=tfplan

      - name: tfsec
        if: ${{ steps.check_dir.outputs.has_tf == 'true' }}
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ inputs.working_dir }}

      - name: Upload plan
        if: ${{ steps.check_dir.outputs.has_tf == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: ${{ inputs.working_dir }}/tfplan
