name: PR & Commit Notification Email

on:
  workflow_call:
    inputs:
      maintainer_email:
        description: "Email address of the maintainer"
        required: true
        type: string
    secrets:
      SMTP_HOST:
        required: true
      SMTP_PORT:
        required: true
      SMTP_USER:
        required: true
      SMTP_PASS:
        required: true

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Nodemailer
        run: npm install nodemailer

      - name: Send Notification Email
        run: |
          node -e "
            const nodemailer = require('nodemailer');
            const port = Number(process.env.SMTP_PORT) || 465;
            const transporter = nodemailer.createTransport({
              host: process.env.SMTP_HOST,
              port,
              secure: port === 465, // SSL for 465
              auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS }
            });

            const isPR = !!process.env.PR_TITLE;
            let subject, htmlContent;

            if (isPR) {
              subject = \`PR Notification: \${process.env.PR_TITLE}\`;
              htmlContent = \`
                <h3>Hello Maintainer,</h3>
                <p>A contributor has submitted or updated a pull request.</p>
                <ul>
                  <li><strong>Contributor:</strong> \${process.env.CONTRIBUTOR}</li>
                  <li><strong>PR Title:</strong> \${process.env.PR_TITLE}</li>
                  <li><strong>PR Link:</strong> <a href='\${process.env.PR_URL}'>View PR</a></li>
                </ul>
              \`;
            } else {
              subject = \`Commit Notification: \${process.env.COMMIT_MESSAGE}\`;
              htmlContent = \`
                <h3>Hello Maintainer,</h3>
                <p>A commit has been pushed to the repository.</p>
                <ul>
                  <li><strong>Branch:</strong> \${process.env.BRANCH}</li>
                  <li><strong>Committer:</strong> \${process.env.COMMITTER}</li>
                  <li><strong>Message:</strong> \${process.env.COMMIT_MESSAGE}</li>
                  <li><strong>Commit Link:</strong> <a href='\${process.env.COMMIT_URL}'>View Commit</a></li>
                </ul>
              \`;
            }

            const mailOptions = {
              from: process.env.SMTP_USER,
              to: process.env.MAINTAINER_EMAIL,
              subject,
              html: htmlContent
            };

            transporter.sendMail(mailOptions, (err, info) => {
              if (err) {
                console.error('❌ Email failed:', err);
                process.exit(1);
              } else {
                console.log('✅ Email sent:', info.response);
              }
            });
          "
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAINTAINER_EMAIL: ${{ inputs.maintainer_email }}

          # PR-specific
          PR_TITLE: ${{ github.event.pull_request.title || '' }}
          PR_URL: ${{ github.event.pull_request.html_url || '' }}
          CONTRIBUTOR: ${{ github.event.pull_request.user.login || '' }}

          # Push-specific
          BRANCH: ${{ github.ref_name || '' }}
          COMMITTER: ${{ github.actor || '' }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message || '' }}
          COMMIT_URL: ${{ github.event.head_commit.url || '' }}
