name: SAST (Semgrep)

on:
  workflow_call:
    inputs:
      config:
        description: "Semgrep config (e.g., 'p/ci' or 'auto')"
        type: string
        default: "auto"
      fail_on:
        description: "Fail on levels (critical, high, medium). CSV"
        type: string
        default: "high,critical"

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # if you upload SARIF
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v2
        with:
          config: ${{ inputs.config }}
          generateSarif: true
          publishToken: ""    # not publishing to Semgrep App
        env:
          SEMGREP_RULES: ${{ inputs.config }}

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
