name: Secret Detection

on:
  workflow_call:
    inputs:
      baseline:
        type: string
        default: ".secrets.baseline"
      fail_on_new_secrets:
        type: boolean
        default: true

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install detect-secrets
      - run: |
          if [ -f "${{ inputs.baseline }}" ]; then
            detect-secrets scan --baseline ${{ inputs.baseline }} --all-files > scan.json || true
            detect-secrets audit --json scan.json || true
          else
            detect-secrets scan --all-files > scan.json || true
          fi
      - name: Fail if new secrets found
        if: ${{ inputs.fail_on_new_secrets }}
        run: |
          if jq '.results | length > 0' -e scan.json >/dev/null 2>&1; then
            echo "Secrets detected!"
            exit 1
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: secret-scan
          path: scan.json
